AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  name:
    Type: String
    Description: bucket name

Resources:
  bucket: 
    Type: "AWS::S3::Bucket"
    Properties: 
      BucketName: '|Ref|name' 

Output:
  name:
    Value: '|Ref|bucket'
    Description: Name of the bucket
